server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stickyNotes

    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true